using Dotty.Terminal.Pty;

namespace Dotty.Terminal.Hosting;

/// <summary>
/// Applies a <see cref="PromptHint"/> to a zsh session by pointing ZDOTDIR at a
/// generated directory whose rc files source the user's real ones and then set
/// PROMPT. This is the same technique VS Code and Warp use for shell integration:
/// injecting PROMPT through the environment alone doesn't work because the user's
/// ~/.zshrc runs after the environment is applied and resets the prompt.
/// </summary>
internal static class ZshPromptShim
{
    /// <summary>
    /// If the hint is set and the target shell is zsh, writes the shim directory
    /// and redirects ZDOTDIR in <paramref name="config"/>. Returns the shim
    /// directory path (for cleanup on session dispose), or null when the hint
    /// does not apply.
    /// </summary>
    internal static string? Apply(PromptHint hint, PtyConfig config)
    {
        if (hint == PromptHint.None)
            return null;

        string shell = config.Shell
            ?? Environment.GetEnvironmentVariable("SHELL")
            ?? "/bin/sh";
        if (Path.GetFileName(shell) != "zsh")
            return null;

        string prompt = GetZshPrompt(hint);
        string shimDirectory = Path.Combine(Path.GetTempPath(), $"dotty-prompt-{Guid.NewGuid():N}");
        try
        {
            Directory.CreateDirectory(shimDirectory);

            WriteForwardingRc(shimDirectory, ".zshenv");
            WriteForwardingRc(shimDirectory, ".zprofile");
            WriteForwardingRc(shimDirectory, ".zlogin");
            File.WriteAllText(Path.Combine(shimDirectory, ".zshrc"),
                $$"""
                # Generated by Dotty. Sources the user's .zshrc, then applies the
                # prompt hint requested by the embedding application.
                _dotty_user_zdotdir="${DOTTY_USER_ZDOTDIR:-$HOME}"
                [[ -f "$_dotty_user_zdotdir/.zshrc" ]] && . "$_dotty_user_zdotdir/.zshrc"
                unset _dotty_user_zdotdir
                PROMPT={{prompt}}
                """ + "\n");
        }
        catch
        {
            if (Directory.Exists(shimDirectory))
                Cleanup(shimDirectory);
            throw;
        }
        // Remember where the user's real config lives so the shim can source it.
        // Precedence mirrors the spawn path: host-supplied env wins over inherited.
        string? userZdotdir = config.Env.TryGetValue("ZDOTDIR", out string? fromHost)
            ? fromHost
            : Environment.GetEnvironmentVariable("ZDOTDIR");
        if (userZdotdir != null)
            config.Env["DOTTY_USER_ZDOTDIR"] = userZdotdir;

        config.Env["ZDOTDIR"] = shimDirectory;
        return shimDirectory;
    }

    internal static string GetZshPrompt(PromptHint hint) => hint switch
    {
        PromptHint.Directory => "'%1~ %# '",
        PromptHint.DirectoryArrow => "'%F{cyan}%1~%f %(?.%F{magenta}.%F{red})❯%f '",
        PromptHint.ParentAndDirectory => "'%2~ %# '",
        _ => throw new ArgumentOutOfRangeException(nameof(hint), hint, null),
    };

    private static void WriteForwardingRc(string shimDirectory, string fileName)
    {
        File.WriteAllText(Path.Combine(shimDirectory, fileName),
            $$"""
            # Generated by Dotty. Forwards to the user's real {{fileName}}.
            _dotty_user_zdotdir="${DOTTY_USER_ZDOTDIR:-$HOME}"
            [[ -f "$_dotty_user_zdotdir/{{fileName}}" ]] && . "$_dotty_user_zdotdir/{{fileName}}"
            unset _dotty_user_zdotdir
            """ + "\n");
    }

    internal static void Cleanup(string? shimDirectory)
    {
        if (shimDirectory == null || !Directory.Exists(shimDirectory))
            return;

        try
        {
            Directory.Delete(shimDirectory, recursive: true);
        }
        catch (IOException) { }
        catch (UnauthorizedAccessException) { }
        catch (DirectoryNotFoundException) { }
}
